# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SakeBoard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  pod 'React', :path => rn_path, :subspecs => [
    'RCTLinkingIOS',
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"
  pod 'Firebase/Core'
end
